---
title: "On the Surgical Removal of Cardassian Cranial Implants: A case study of a Cardassian patient"
date: 2178-09-09
format:
  html:
    css: styles.css
    highlight-style: a11y
author:
  - name: Julian Bashir
    orcid: 0009-0003-6465-6658
    affiliation: Starbase Deep Space Nine
  - name: Elim Garak
    url: https://www.jpmonteagudo.com/
    orcid: 0009-0003-6465-6658
    affiliation: Starbase Deep Space Nine
categories: 
  - Cranial Implants
  - Space Travel
  - Surgery
  - Mock-up
  - Placeholder
pub-info:
  reference: >-
    <a href="https://www.jpmonteagudo.com"/>Julian Bashir</a> and <strong>Elim Garak</strong>, “On the Surgical Removal of Cardassian Cranial Implants: A case study of a Cardassian patient” <em>Starbase Deep Nine Archives</em> 130, no. 9 (September 2178): 1425–1439
  links:
  - name: Preprint
    url: hikmah-testing-default-manuscript.pdf
    icon: fa-solid fa-file-pdf
    local: true
  - name: Final version
    #url: https://doi.org/10.1111/oik.07621
    icon: fa-solid fa-scroll
  - name: Code
    url: https://github.com/jpmonteagudo28/hikmah-academic-quarto
    icon: fa-brands fa-github
  - name: Add to Mendeley
    url: https://www.mendeley.com/search/
    icon: fa-brands fa-mendeley
#doi: 10.1111/oik.07621
haiku: 
 - These brain distortions–
 - horse loose in a hospital.
 - Surgery?...Proceed.
---

## Important links

- [Paper (preprint)](hikmah-testing-default-manuscript.pdf)
- [Statistical analysis notebook](https://github.com/jpmonteagudo28/hikmah-academic-quarto)
- [GitHub repository](https://github.com/jpmonteagudo28/hikmah-academic-quarto)

## Abstract

I have reset the sensors to scan for frequencies outside the usual range. By emitting harmonic vibrations to shatter the lattices. We will monitor and adjust the frequency of the resonators. He has this ability of instantly interpreting and extrapolating any verbal communication he hears. It may be due to the envelope over the structure, causing hydrogen-carbon helix patterns throughout. I'm comparing the molecular integrity of that bubble against our phasers.


## Important notes

Stellar flares are increasing in magnitude and frequency. Set course for Rhomboid Dronegar 006, warp seven. There's no evidence of an advanced communication network. Total guidance system failure, with less than 24 hours' reserve power. Shield effectiveness has been reduced 12 percent. We have covered the area in a spherical pattern which a ship without warp drive could cross in the given time.

Resistance is futile.


## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.mendeley.com/search/">&emsp;Add to Mendeley {{< fa square-arrow-up-right >}}</a>
</p>

```bibtex
@article{BashirGarak:2178,
    Author = {Julian Bashier and Elim Garak},
    Journal = {Starbase Deep Space Nine},
    Month = {9},
    Number = {9},
    Pages = {1425--1439},
    Title = {On the Surgical Removal of Cardassian Cranial Implants: A case study of a Cardassian patient},
    Volume = {130},
    Year = {2178}}
```