---
title: "What's this CLT, please? A straightforward explanation of the Central Limit Theorem and the magic ($n =30$) sample size requirements"
date: 2024-03-06
description: "Shining a light on the Central Limit Theorem and the mythical sample size requirements for the health and social sciences"
categories:
 - r
 - clt
 - sample size
 - t–test
 - normal distribution
 - statistics
 - Gaussian
 - random variables
format:
  html:
    code-fold: true
    code-tools: true
doi: 10.59350/bje88-8r592
citation: true
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.retina = 3,
                      fig.width = 5.5, fig.height = (5.5 * 0.618),
                      out.width = "90%", collapse = TRUE)
options(digits = 3, width = 300)
```

## The Central Limit Theorem

The rudiments of the Central Limit Theorem (CLT) can be traced back to Bernoulli, who famously penned: “even the stupidest person without any prior instruction knows that the more observations are made, the less danger there is of missing the target”, hinting at the notion that, as the number of trials increases, even a simpleton is likely to eventually arrive at the expected outcome.

The theorem derives its name from the fact that we're using a parameter of *central* tendency – typically the mean, median, or mode– to arrive at the *limiting distribution* of independent random variables– which, under certain conditions, will typically be the standard normal distribution. 

To put it differently, by sampling a finite population an increasing number of times and using the mean of the $n$ samples as our metric, we will see how our histogram for the population of sampled means will conform to a standard normal curve. By estimating the limiting distribution– the beloved normal distribution– of our independent variables, the theorem helps us answer the question:

> If an outcome $p$ has occurred $p$ times out of $p + q = n$ number of trials, what's the probability of our desired outcome occurring $r$ times in a further $r + q = m$ number of trials?

Let's now talk about the *conditions* we must meet for our distribution to converge or arrive at the standard normal distribution with mean equal to zero and variance equal to 1.

::: column-margin
I'll start referring to a standard normal distribution with mean equal to zero and variance equal to 1 by using the following notation

$$\mathcal{N}(0,1)$$
:::

### Random processes

The variables under study must be the outcome of a random phenomenon for which we know the type of outcomes that can happen but cannot know how or when they will occur. We can know some of the causes of this phenomenon, but their deviations from a supposed pattern are unknown to us.

A classic example of a random variable is a game of cards in which we know what the cards on the deck are but cannot tell which one will come up next– unless we cheat and then the whole thing is not a random phenomenon anymore. In the life and social sciences, we can find random variables everywhere: the height and weight of a population, hemoglobin levels in healthy adults, the number of patients in the ER on any given night, pH levels in different types of topsoil or the scores on the UCLA Loneliness scale. The common thread here is that one *random* observation doesn't provide information on the occurrence of the next one.

### Independence and identical distribution

In the life and social sciences, we'll typically see *conditional independence*, where variables $A$ and $B$ are measurements of the same underlying quantity $C$. We say that $A$ and $B$ are conditionally independent if, once C is known, the value of $B$ doesn't give new information about $A$. Knowing what happens to $B$ after $C$ takes place doesn't increase our chances of correctly predicting the outcome of $A$. In addition, independent variables are also uncorrelated – their covariance ($cov[A,B] = E[A]\cdot E[B]$) and Pearson's $r$ ($\rho_{X,Y} = \frac{cov[A,B]}{\sigma_{A}\sigma_{B}}$) are equal to zero.

```{mermaid}
---
title: Conditional independence
---
flowchart LR
C((C))<---> A([A])
C((C))<---> B([B])
A([A])<-.No effect.->B([B])
```



Two variables $A_{n}$ and $B_{n}$ are identically distributed when their probability distributions match exactly, and their means and variances ($\mu_{A} = \mu_{B}, \sigma_{A}^2 = \sigma_{B}^2$) are equal. By now you can already see how this assumption can at best be approximated and almost impossible to demonstrate by the variables commonly studied in the life and social sciences.

### Additive processes

 A process $Y$ is  considered additive

::: column-margin
$$
Y_{i} = Y(0) + Y_{1}(i) + Y_{2}(i), i \geq 0 \\
\text{where} Y(0) = f(i),  \text{is a non-random function}
$$
:::

when the value of each observation is determined by adding a variable quantity to the value of a previous observation. The process is characterized by an initial value $Y(0)$ and the increments $Y_{i} - Y_{h}$ with $i > h \geq 0$, where $Y_{i}$ represents the value of an observation at a certain point and $Y_{h}$, the value of the subsequent observation. This additive process typically consists of three components. 

+ An initial value $Y_{0}$ that serves as the starting point of the process.

+ A random, slow, and gradual change component $Y_{1}$ around the central tendency represents the continuous evolution of the process over time.

+ A third random component $Y_{2}$​ represents sudden jumps or changes in the process, which may occur unpredictably at certain time points.

Together, these components contribute to the behavior of the $Y$ process and its evolution across time through a combination of unexpected slow changes and sudden jumps.

-   How we use CLT

-   How to know when empirical distribution converges to normal distribution?

    ### what's the deal with $n \geq 30$?

    -   Jacob Cohen (1991) mentioned that at least 30 observations were needed to use the critical-ratio approach used in t-tables when comparing groups. If the sample size is smaller than 30, then students would be forced to “small” sample statistics.

        > It wasn't until some years later that I discovered (mind you, not invented) power analysis, one of whose fruits was the revelation that for a two-independent-group-mean comparison with n = 30 per group at the sanctified two-tailed .05 level, the probability that a medium-sized effect would be labeled as significant by the most modern methods (a t-test) was only .47. Thus, it was approximately a coin flip whether one would get a significant result, even though, in reality, the effect size was meaningful.

        -   Simply a rule of thumb that allowed students to use critical t–t-tables. These tables could only span 30 lines to fit in one page. Fisher created the

            t-table and only went up to n = 30 (Fisher's *Statistical Methods for Research Workers* (1925))

        -   Sample size at least 30 so that the error variance between t–t-distribution and theoretical normal distribution is .25 or less from df = 30 up to infinity.

        -   When data is severely skewed neither the t–test nor the permutation test have much power (are not robust) to correctly identify a statistically significance difference in means between too highly skewed distributions. Even if your data contained tens of thousands of observations, the t–test may not recognize a statistically significance difference in means. The distribution of the data and the number of observations need to be considered when deciding whether the t–test is meaningful and accurate, sometimes thousands of observations may be needed.

    ## Solution

    -   The number of observations needed for our distribution to approximate the standard normal curve will ultimately depend on our data, the question we're seeking to answer, and the test we plan to use to arrive at our hypothesis.
    -   Use power analysis to determine the sample size needed to obtain statistically significant results using your desired $\alpha$, $\beta$, and effect size measure. This way, you don't have to assume
